import type { AuthConfig } from "./types";

export const config = {
	enableAnonymousTrial: true,
	enableSignup: true,
	enableMagicLink: true,
	enableSocialLogin: true,
	enablePasskeys: true,
	enablePasswordLogin: true,
	enableTwoFactor: true,
	sessionCookieMaxAge: 60 * 60 * 24 * 30,
	users: {
		enableOnboarding: true,
	},
	organizations: {
		enable: true,
		hideOrganization: false,
		enableUsersToCreateOrganizations: true,
		requireOrganization: false,
		forbiddenOrganizationSlugs: [
			"admin",
			"ai-demo",
			"api",
			"assets",
			"blog",
			"changelog",
			"chatbot",
			"checkout-return",
			"choose-plan",
			"contact",
			"create",
			"credit-pack-checkout-return",
			"dashboard",
			"docs",
			"draft",
			"edits",
			"examples",
			"forgot-password",
			"history",
			"icon.png",
			"image-proxy",
			"image-to-image",
			"llms-full.txt",
			"llms.mdx",
			"llms.txt",
			"login",
			"models",
			"new-organization",
			"og",
			"onboarding",
			"opengraph-image",
			"organization-invitation",
			"pricing",
			"privacy",
			"reset-password",
			"robots.txt",
			"settings",
			"signup",
			"sitemap.xml",
			"terms",
			"try",
			"verify",
		],
	},
} as const satisfies AuthConfig;
