ALTER TYPE "GenerationJobStatus"
  ADD VALUE IF NOT EXISTS 'NEEDS_RECONCILIATION' AFTER 'PROVIDER_RUNNING';

ALTER TYPE "GenerationAttemptStatus"
  ADD VALUE IF NOT EXISTS 'NEEDS_RECONCILIATION' AFTER 'RUNNING';
